name: 'list pul requests'
description: 'list pull requests.'
author: 'mike'
inputs:
  token:
    description: 'The GITHUB_TOKEN used to authenticate to the current repository'
    required: true
outputs:
  prs:
    description: 'The URL of the GitHub release that was drafted'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  color: orange
  icon: tag
