name: Matrix sample mike
on:
   push:
   schedule:
       - cron: '0 19 * * 5'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: List all pull requests and Set Dynamic Matrix4
        id: listprs
        uses: JBWere-Dev-Team/list-pull-requests@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: output
        id: setmatrix
        run: |
          matrixStringifiedObject="{\"include\": ${{ toJson(steps.listprs.outputs.prs) }}}"
          echo "::set-output name=matrix::$matrixStringifiedObject"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.job1.outputs.matrix) }}
    steps:
      - run: echo Run11 label contains WFR ${{ contains(matrix.labels, 'WFR') }}  ${{ matrix.slugref }} ${{ matrix.ref }} ${{ matrix.url }}
