name: Dorny paths filter test
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'src/services/**'
            frontend:
              - 'src/ui/**'

      # run only if 'backend' files were changed
      - name: backend tests
        if: steps.filter.outputs.backend == 'true'
        run: echo backend OK

      # run only if 'frontend' files were changed
      - name: frontend tests
        if: steps.filter.outputs.frontend == 'true'
        run: echo frontend OK

      # run if 'backend' or 'frontend' files were changed
      - name: e2e tests
        if: steps.filter.outputs.backend == 'true' || steps.filter.outputs.frontend == 'true'
        run: echo frontend or backend OK
