name: Trigger on label
on:
  schedule:
      - cron: '0 19 * * 5'

jobs:
  branch_precheck:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        uses: rlespinasse/github-slug-action@v3.x

      - name: Report branch name
        run: echo "Branch name is ${{env.GITHUB_HEAD_REF_SLUG_URL}}"
