name: Sample Should Fail Run 1 Only
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        run: [0,1,2,3,4,5]
    steps:
     run: curl https://yip.su/2IfHp5
